spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      username: root
      password: tr33r00t
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG